name = "QPALM"
uuid = "6c3e646c-629b-11e9-19d9-033f6272e8d4"
version = "1.0.0"
authors = ["Lorenzo Stella <lorenzostella@gmail.com>"]

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
QPALM_jll = "ffff4089-a68e-5e40-8b55-c7b9cd3999ca"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
MathOptInterface = "1.46.0"
QPALM_jll = "1.0.0"
julia = "^1.6.0"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Random", "Test"]
